package practical.innerClass;

public class InnerClass_StaticNestedClass {

	static int data=30;  
	  static class Inner{  
	   void msg(){System.out.println("data is "+data);}  
	  }  
	  public static void main(String args[]){  
		  InnerClass_StaticNestedClass.Inner obj=new InnerClass_StaticNestedClass.Inner();  
	  obj.msg();  
	  }  

}

/*
Internal class generated by the compiler

import java.io.PrintStream;  
static class TestOuter1$Inner  
{  
TestOuter1$Inner(){}  
void msg(){  
System.out.println((new StringBuilder()).append("data is ")  
.append(TestOuter1.data).toString());  
}    
}  

*/