package practical.innerClass;

public class InnerClass_AnonymousInnerClassUsingInterface {

	public static void main(String args[]){  
		 Eatable e=new Eatable(){  
		  public void eat(){System.out.println("nice fruits");}  
		 };  
		 e.eat();  
		 }  

}
interface Eatable{  
	 void eat();  
	}

/*
Internal class generated by the compiler

import java.io.PrintStream;  
static class TestAnonymousInner1$1 implements Eatable  
{  
TestAnonymousInner1$1(){}  
void eat(){System.out.println("nice fruits");}  
}  
*/